---
preconfig_tasks:
    - tasks/ansible_flags.yml

packages_to_install:
    - git
    - vim-gtk
    - vim
    - i3
    - docker-compose
    - tree
    - python3-pip
    - curl
    - wget

    - make 
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - python-openssl

pip_modules_to_install:
    - ansible
    - pylint
    - black
    - mypy

ssh_files:
    - id_rsa
    - id_rsa.pub
    - config

python_version: "3.8.2"

