---
- name: Update apt cache
  apt: update_cache=true
  become: yes

- name: Ensure apt dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  become: yes

- name: Add Puppet Labs apt key
  apt_key:
    url: https://apt.puppetlabs.com/DEB-GPG-KEY-puppetlabs
    state: present
  become: yes

- name: Add Puppet Labs repository
  apt:
    deb: "https://apt.puppetlabs.com/puppet6-release-{{ ansible_distribution_release }}.deb"
    state: present
  register: puppet_apt_deb_install
  become: yes

- name: Update apt cache if necessary
  apt: update_cache=true
  when: puppet_apt_deb_install.changed
  become: yes

- name: Install Puppet
  package:
    name: puppetserver
    state: present
  become: yes
  
- name: Set puppetserver memory options
  lineinfile:
    path: /etc/default/puppetserver
    regexp: 'JAVA_ARGS="-Xms\d*\w -Xmx\d*\w .*'
    line: JAVA_ARGS="-Xms512m -Xmx512m -Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger"
  become: yes

- name: Add puppet server as puppet agent
  blockinfile:
    block: |
      [agent]
      server = master.vm
    path: "/etc/puppetlabs/puppet/puppet.conf"
    insertafter: EOF
    marker: '#{mark} ANSIBLE MANAGED BLOCK PUPPET'
    state: present
  become: yes

- name: Add Puppet bin to root PATH in bashrc
  blockinfile:
    block: |
      export PATH="/opt/puppetlabs/bin:${PATH}"
    path: "/root/.bashrc"
    insertafter: EOF
    marker: '#{mark} ANSIBLE MANAGED BLOCK PUPPET'
    state: present
  become: yes

- name: Add Puppets ruby to root PATH in bashrc
  blockinfile:
    block: |
      export PATH="/opt/puppetlabs/puppet/bin:${PATH}"
    path: "/root/.bashrc"
    insertafter: EOF
    marker: '#{mark} ANSIBLE MANAGED BLOCK PUPPET'
    state: present
  become: yes  

- name: Ensure Puppet service is started and enabled at boot
  service:
    name: puppetserver
    state: started
    enabled: true
  become: yes