
---
  - name: Install packages necessary for a new system
    apt:
      update_cache: yes
      state: present
      autoclean: yes
      autoremove: yes
      name: "{{ packages_to_install|list }}"
    become: yes
  
  - name: Install vs code
    snap:
      name: code
      classic: yes
      state: present
    become: yes

  - name: Add user to docker group
    user:
      name: "{{ansible_user}}"
      groups: docker, sudo, plugdev, adm
    become: yes
