---
- name: Check if vagrant is installed
  stat:
    path: "{{ ansible_env.HOME }}/bin/vagrant"
  register: vagrant

- name: Create a symbolic link for vagrant
  file:
    src: /mnt/c/HashiCorp/Vagrant/bin/vagrant.exe
    dest: "{{ ansible_env.HOME }}/bin/vagrant"
    state: link
  when: not vagrant.stat.exists

- name: Add Vagrant environment variables to bashrc
  blockinfile:
    block: |
      export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
    path: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    marker: '#{mark} ANSIBLE MANAGED BLOCK VAGRANT'
    state: present
