
---
- name: Ensure .ssh directory exists.
  file: 
    dest: "{{ ansible_env.HOME }}/.ssh"
    mode: 0700 
    state: directory

- name: Install ssh key
  copy: 
    src: "common/{{ item }}" 
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
    mode: 0600
  with_items: "{{ ssh_files }}"

  #- name: Set authorized key
  #authorized_key:
  #  user: "{{ansible_user}}"
  #  state: present
  #  key: "{{ lookup('file', 'common/id_rsa.pub') }}"
